### PR TITLE
feat: update header layout

### PR DESCRIPTION
**Pull request by fairlighteth**
# Description

- Addresses https://github.com/cowprotocol/docs/issues/282 

Screenshot 2024-01-15 at 12 30 09
Screenshot 2024-01-15 at 12 29 56
Screenshot 2024-01-15 at 12 29 45

### CODE REVIEW

**Review by mfw78 — APPROVED** [review]

**Review by alfetopito — APPROVED** [review]

**Review by anxolin — COMMENTED** [review]
Could we pass the linter to the whole project so the automatic linter in our IDE don't add additional unrelated changes for a PR?

**Comment by elena-zh** [comment]
Heya @fairlighteth , I still can find 1 nitpick in the menu. Not a priority, though :) 
image

**Comment by fairlighteth** [comment]
@elena-zh Leaving it for now. This is default behavior that it applies text ellipsis. If we really want we could replace the text with 'docs'. But don't see it worth the squeeze at the moment :)

**Comment by mfw78** [comment]
> Could we pass the linter to the whole project so the automatic linter in our IDE don't add additional unrelated changes for a PR?

FYI, repo-wide linting is slated to happen in #225.

**Pull request merged**
