### PR TITLE
feat: autogenerated sidebar structure

### LINKED ISSUE #150: chore: sidebars / footer links configured

### PR DESCRIPTION
**Pull request by fairlighteth**
# Description

Screenshot 2023-11-30 at 17 13 01

- Re-organizes the sidebar menu structure.
- Adds emojis for visual cues
- Set autogenerated sidebar basded on file structure in the docs folder:
Screenshot 2023-11-30 at 17 13 22

## To review:
1. These items needs to be reviewed and moved to a better sub folder: 
Screenshot 2023-11-30 at 17 13 13

2. Review the sidebar structure for correctness.

## Related issues

Fixes: #150

### CODE REVIEW

**Comment by marshymarsh** [comment]
Love this PR. Some comments:

- I would have Overview, CoW Protocol, MEV Blocker, and Governance be the top-line items (for MEV Blocker we would need to have some sort of "coming soon" page there)
- Then under CoW Protocol I would have Concepts, Tutorials, and Technical Reference, as they are now
- Agree you should never be able to read any of these pages without seeing the nav at left. The "CoW DAO" page should be under "Overview"
- I would also suggest moving "Definitions" under "Overview"
- I would have shortcuts to each of the top-line items in the top nav bar. Like this: 

Screenshot 2023-11-30 at 8 24 18 PM

- (This also fixes what is currently a fairly-strange top nav layout for mobile, where "CoW Documentation" is in the top-right.)

Screenshot 2023-11-30 at 8 12 40 PM

(this looks weird)


- Would remove the "(Batch Auctions)" after "CoW Protocol" in the left-nav
- Some items in the left nav (like "scripts" and "programmatic") are not capitalized ... we should consistently capitalize the first letter of every menu item
- I propose reordering the CoW Swap section under Tutorials as follows: Market Orders (Swaps), Limit Orders, TWAP Orders, Wrapping Native Tokens, Cancelling Orders
- I find it confusing that some toggle list items are able to be opened (i.e. Tutorials > CoW Swap) and others are not (i.e. Concepts > Introduction). We should be consistent and, in my view, apply the latter example to all toggles (and migrate content that is currently there to a sub-page). That way no content is at risk of being missed. 

Cheers,

**Comment by MindyCoW** [comment]
Co-signing Alex's proposed changes.

**Comment by mfw78** [comment]
On reviewing this PR:
1. The movement of `cow-protocol` sub-documents into the higher level directory is not valid with the intent as there is also scope to include MEV Blocker documentation. Therefore the documentation is split out by products (CoW Protocol & MEV Blocker) plus Governance.
2. Changes to design as mentioned in the comment by @marshymarsh are better suited for separate issues, as opposed to this PR (sticking to the purpose of the PR, being autogenerated structure). I'll create a new issue to track these comments so we can avoid having large monolithic PRs while the codebase is moving at high velocity and avoid merge conflicts as much as possible.
3. There appears to be a linter pass that has been done on the codebase by some local-specific linter rule which is exacerbating the number of changes.

**Comment by mfw78** [comment]
This PR is superceded by #227

**Comment by mfw78** [comment]
Superseded by #227

**Pull request closed without merging**
