### PR TITLE
Update README.mdx

### PR DESCRIPTION
**Pull request by MindyCoW**
Fixed 2 typos and added a section at the bottom to further help the user navigate quickly to Concepts, Tutorials or Technical Reference.

# Description

# Changes

- [ ] ...
- [ ] ...

### CODE REVIEW

**Comment by MindyCoW** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by MindyCoW** [comment]
recheck

**Comment by mfw78** [comment]
In order to maintain consistency, I'd suggest that the expanded section for navigation links underneath be in the same order as the navbar, or better yet, we can remove the expanded section for navigation, and just enforce that the navbar is open on this page (otherwise we can get a disconnect between the page and the navbar)

**Comment by MindyCoW** [comment]
I'm not opposed to changing the order so it matches the navbar. But personally, I didn't notice the navbar at first (because it's not there on the docs landing page), so I was confused about where to navigate next. For a user who lands on docs -> clicks CoW Protocol -> starts scanning for info on CoW Swap, a more explicit information trail is needed than just the navbar IMO.

**Comment by mfw78** [comment]
Cool, I'll push changes to the PR to modify the order to adhere to the navbar. Navbar methodology looks like it's going to be handled in #180, so if you have UX issues related specifically to the navbar, that'd be a great place to put them :grinning:

**Comment by mfw78** [comment]
Changes merged in #195

**Comment by mfw78** [comment]
Changes merged in #195

**Pull request closed without merging**
