### PR TITLE
Cow amm updates

### PR DESCRIPTION
**Pull request by gogonimago**
# Description

# Changes

- [ ] ...
- [ ] ...

### CODE REVIEW

**Comment by cowmarketing** [comment]
Unsure if we want to have this section: https://docs-git-cowammupdates-cowswap.vercel.app/cow-amm/tutorials/cow-amm since its not the go to anymore. For that reason, and since we want more people to use Balancers, I would just simply delete it. Maybe @mfw78 can chime in here in terms of if to delete or leave.

**Comment by cowmarketing** [comment]
Additionally, since we already have it, would add this step by step guide: https://x.com/CoWSwap/status/1826257683030417710

**Comment by mfw78** [comment]
> Unsure if we want to have this section: https://docs-git-cowammupdates-cowswap.vercel.app/cow-amm/tutorials/cow-amm since its not the go to anymore. For that reason, and since we want more people to use Balancers, I would just simply delete it. Maybe @mfw78 can chime in here in terms of if to delete or leave.

IMO, this can be deleted.

**Review by cowmarketing — APPROVED** [review]

**Review by mfw78 — APPROVED** [review]
Approved for the removal of `cow-amm` contract technical reference. On a glance, there are still typographical errors associated with quotations and apostrophes not being strictly `"` and `'`.

**Pull request merged**
