### PR TITLE
[fix] typos in doc

### PR DESCRIPTION
**Pull request by WardenJakx**
# Description

The docs for "how to submit orders via the api" had a typo in placing the order, saying the signature was gotten from step 4, when it was really step 3

the reason for this was a miscount in the naming of the files. 

additionally, step 2 should be named "-get-a-quote" to match the style of the other files in that directly being named as the title of the page

### CODE REVIEW

**Comment by WardenJakx** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by WardenJakx** [comment]
recheck

**Comment by WardenJakx** [comment]
recheck

**Comment by mfw78** [comment]
Thanks for reporting. This repo is a heavy WIP and is more of a beta / staging environment at the moment for docs that are undergoing heavy iteration.

**Pull request closed without merging**
