### PR TITLE
Add safe-dapp tutorials

### PR DESCRIPTION
**Pull request by anxolin**
# Description

This PR adds a **new tutorial** that makes it easier to create a Safe Dapp that uses CoW Swap!

image

## Test
See 
https://docs-git-your-custom-safe-dapp-cowswap.vercel.app/cow-protocol/tutorials/swap-in-safe-app

### CODE REVIEW

**Comment by mfw78** [comment]
Interesting idea. In general, I think we should make it more imperative that the point of this is about integrating the widget into a safe app as at the moment it may read a little like "how to build a safe app" with the widget being an after thought.

**Comment by anxolin** [comment]
@mfw78 I just renamed it to 
image

**Comment by elena-zh** [comment]
Hey @anxolin , great job!
There are some typos in the text: 
testnet
your

And some missing periods:
period 1
period
periods
image

**Comment by elena-zh** [comment]
@anxo, still some periods are missing :) 
image

**Review by elena-zh — APPROVED** [review]

**Comment by anxolin** [comment]
> @Anxo, still some periods are missing :)

I thought it was the same as this one! never mind.
https://github.com/cowprotocol/docs/pull/349/commits/447f42689fdb363a35ebb71322177443fd2739bc#diff-2a1c9042daf11cf028cf868905c04cd1c3dd4eb825500f01ac3620e474dfc03dR41


Thanks for re-checking

**Review by alfetopito — APPROVED** [review]

**Pull request merged**
